--PART-A

--1
SELECT *FROM Deposite
--2
SELECT *FROM Borrow
--3
SELECT *FRoM Customers
--4
SELECT  ACTNO,CNAME,AMOUNT FROM Deposite
--5
SELECT LOANNO,AMOUNT FROM BORROW
--6
SELECT * FROM BORROW 
WHERE BNAME = 'ANDHERI'
--7
SELECT ACTNO,AMOUNT FROM DEPOSIT
WHERE ACTNO = 106
--8
SELECT CNAME FROM BORROW
WHERE AMOUNT > 5000
--9
SELECT CNAME FROM BORROW
WHERE ADATE > '1996-12-01'
--10
SELECT CNAME FROM DEPOSIT
WHERE ACTNO < 105
--11
SELECT CNAME FROM CUSTOMERS
WHERE CITY='NAGPUR' OR CITY='DELHI'

SELECT CNAME FROM CUSTOMERS
WHERE CITY IN('NAGPUR','DELHI')
--12
SELECT CNAME,BNAME FROM DEPOSIT
WHERE AMOUNT > 4000 AND ACTNO < 105
--13
SELECT CNAME FROM BORROW
WHERE AMOUNT >= 3000 AND AMOUNT <= 8000

SELECT CNAME FROM BORROW
WHERE AMOUNT BETWEEN 3000 AND 8000
--14
SELECT CNAME FROM DEPOSIT
WHERE BNAME <> 'ANDHERI'
--15
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT 
WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO < 104

-- PART-B




