--1
SELECT *FROM Deposite
--2
SELECT *FROM Borrow
--3
SELECT *FRoM Customers
--4
SELECT  ACTNO,CNAME,AMOUNT FROM Deposite
--5
SELECT LOANNO,AMOUNT FROM BORROW
--6
SELECT *FROM BORROW
WHERE BNAME='ANDHERI'
--7
SELECT ACTNO,AMOUNT FROM DEPOSITE
WHERE ACTNO=106
--8
SELECT CNAME FROM BORROW
WHERE AMOUNT>5000
--9
SELECT CNAME FROM DEPOSITE
WHERE  ADATE>'1995-12-1'
--10
SELECT CNAME FROM DEPOSITE
WHERE ACTNO<105